### ISSUE TITLE
Node version range

### ISSUE THREAD

**Issue by kentcdodds** [bahmutov/condition-node-version#3]
I don't want to lock down the version of node on my build. Could I instead do a version range?

Happy to make a PR if you're game :+1:

Something like:

``` json
"release": {
  "verifyConditions": {
    "path": "condition-node-version",
    "node": "^4",
    "verbose": true // optional
  }
}
```

So in my `.travis.yml` I can do:

```
node_js:
  - '4'
  - '0.12'
  - '0.10'
```

Thoughts?

**Comment by bahmutov** [comment]
Absolutely yes

**Comment by kentcdodds** [comment]
Preparing a PR now :-)
